// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Name = 1,
  FormName = 2,
  Comment = 3,
  Program = 4,
  Listing = 5,
  Spec = 6,
  TypeList = 9,
  Modifier = 12
