// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Name = 1,
  FormName = 2,
  Program = 3,
  Listing = 4,
  Spec = 5,
  TypeList = 8,
  Modifier = 11,
  Comment = 13,
  Newline = 14;
