// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nameTokenizer, formNameTokenizer} from "./parse.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bQYQTOOO_QTO'#CaOOQP'#Cj'#CjQYQTOOOmQUO'#CbO{QSO'#ChOOQP'#Ck'#CkO!QQTO,58{OOQP-E6h-E6hO!`QSO'#CeOOQP,58|,58|O!hQSO,58|O!pQSO,58|O!kQSO,58|OOQP,59S,59SOOQP-E6i-E6iO!xQSO'#ClO!}QSO,59POOQP1G.h1G.hO#VQSO1G.hO#_QSO1G.hOOQO,59W,59WOOQO-E6j-E6jOOQP7+$S7+$SO#dQSO7+$SOOQP<<Gn<<Gn",
  stateData: "#i~OcOSROS~OPPO~OVSO]TOPTXaTX~OQZOW[OZYOdXO~Od^O~OVSO]TOPTaaTa~OY`OZXX~OWcOZbO~OZbOdXO~OdeO~OY`OZXa~OZgOdXO~OZgO~OZiO~O",
  goto: "!VaPPPPPbfPPjPPfPsy!PTQORTUPVQ]SQd[RhcQRORWRQVPR_VQaXRfa",
  nodeNames: "⚠ Name FormName Comment Program Listing Spec ( : TypeList / ) Modifier @",
  maxTerm: 20,
  skippedNodes: [0,3],
  repeatNodeCount: 3,
  tokenData: "#p~R]XYzYZz]^zpqzst!]xy!wyz!|!P!Q#R!Q![#W![!]#f!b!c#k!c!}#W#T#o#W~!PSc~XYzYZz]^zpqz~!bTR~OY!]Z]!]^;'S!];'S;=`!q<%lO!]~!tP;=`<%l!]~!|OV~~#ROZ~~#WOY~~#]Rd~!Q![#W!c!}#W#T#o#W~#kOW~~#pO]~",
  tokenizers: [nameTokenizer, formNameTokenizer, 0],
  topRules: {"Program":[0,4]},
  tokenPrec: 0
})
