// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nameTokenizer, altNameTokenizer} from "./tokens"
import {blankTokenizer, newlineTokenizer, commentTokenizer} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tQYQ!_OOOeQ!_O'#CcOOQm'#Cm'#CmQYQ!_OOO|QzO'#CdO![QxO'#CkOOQm'#Cn'#CnO!aQ!_O,58}OOQm,58},58}OOQm-E6k-E6kOOQW'#Ch'#ChO!xQxO'#CgOOQm,59O,59OO#QQxO,59OO#YQxO,59OO#TQxO,59OOOQm,59V,59VOOQm-E6l-E6lOOQm1G.i1G.iO!VQxO'#CoO#bQxO,59ROOQm1G.j1G.jO#jQxO1G.jO#rQxO1G.jOOQW,59Z,59ZOOQW-E6m-E6mOOQm7+$U7+$UO#wQxO7+$UOOQm<<Gp<<Gp",
  stateData: "#|~OgOSeOS~OPPORQOSQO~OTWOXSO`TOPVXRVXSVXdVX~OQ]OY^O^[OhYO~Oh`O~OTbOXSO`TOPVaRVaSVadVa~O]cO^ZX~OYfO^eO~O^eOhYO~O]cO^Za~O^jOhYO~O^jO~O^lO~O",
  goto: "!bdPPPPPPPeiPPmvPPiP!O!U![TQORTUPVQ_SQg^RkfUZS^fRhcQRORXRQVPRaVQdZRid",
  nodeNames: "⚠ Name AltName Blank Comment InlineComment Program Listing Spec ( SpecSeparator TypeList TypeName / ) Modifier @",
  maxTerm: 24,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "!u~RYXYqpqqxy|yz!R!P!Q!W!Q![!]![!]!k!b!c!p!c!}!]#T#o!]~vQg~XYqpqq~!ROX~~!WO^~~!]O]~~!bRh~!Q![!]!c!}!]#T#o!]~!pOY~~!uO`~",
  tokenizers: [nameTokenizer, altNameTokenizer, blankTokenizer, newlineTokenizer, commentTokenizer, 0],
  topRules: {"Program":[0,6]},
  tokenPrec: 0
})
