// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Name = 1,
  AltName = 2,
  Comment = 3,
  InlineComment = 4,
  Program = 5,
  Listing = 6,
  Spec = 7,
  SpecSeparator = 9,
  TypeList = 10,
  TypeName = 11,
  Modifier = 14,
  Newline = 16
