// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nameTokenizer, altNameTokenizer} from "./tokens"
import {commentTokenizer} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tQVQ]OOObQ]O'#CbOOQT'#Cm'#CmQVQ]OOOyQYO'#CcO!XQWO'#CjOOQT'#Cn'#CnO!^Q]O,58|OOQT,58|,58|OOQT-E6k-E6kOOQO'#Cg'#CgO!uQWO'#CfOOQT,58},58}O!}QWO,58}O#VQWO,58}O#QQWO,58}OOQT,59U,59UOOQT-E6l-E6lOOQT1G.h1G.hO!SQWO'#CoO#_QWO,59QOOQT1G.i1G.iO#gQWO1G.iO#oQWO1G.iOOQO,59Z,59ZOOQO-E6m-E6mOOQT7+$T7+$TO#tQWO7+$TOOQT<<Go<<Go",
  stateData: "#y~OfOS~OPPORQO`QO~OSWOWSO_TOPUXRUX`UXdUX~OQ]OX^O][OgYO~Og`O~OSbOWSO_TOPUaRUa`UadUa~O[cO]YX~OXfO]eO~O]eOgYO~O[cO]Ya~O]jOgYO~O]jO~O]lO~O",
  goto: "!bdPPPPPPeiPPmvPPiPP!O!U![TQORTUPVQ_SQg^RkfUZS^fRhcQRORXRQVPRaVQdZRid",
  nodeNames: "⚠ Name AltName Comment InlineComment Program Listing Spec ( SpecSeparator TypeList TypeName / ) Modifier @ Newline",
  maxTerm: 23,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "!}~RZXYtYZ!Ppqtxy!Uyz!Z!P!Q!`!Q![!e![!]!s!b!c!x!c!}!e#T#o!e~yQf~XYtpqt~!UO`~~!ZOW~~!`O]~~!eO[~~!jRg~!Q![!e!c!}!e#T#o!e~!xOX~~!}O_~",
  tokenizers: [nameTokenizer, altNameTokenizer, commentTokenizer, 0],
  topRules: {"Program":[0,5]},
  tokenPrec: 0
})
