// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Name = 1,
  AltName = 2,
  Blank = 3,
  newline = 21,
  Comment = 4,
  InlineComment = 5,
  Program = 6,
  Listing = 7,
  Spec = 8,
  SpecSeparator = 10,
  TypeList = 11,
  TypeName = 12,
  Modifier = 15
