name: Mirror to Beta Preview

on:
  push:
    branches: "rewrite"
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: tipsypastels/stardex
          path: ./this
          ref: rewrite

      - name: Copy repository
        run: cp -a this beta

      - name: Commit to beta
        run: |
          cd beta
          rm -rf .git

          git init
          git add -A .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Push to beta."
          git remote add origin https://${{ secrets.COPY_TO_BETA_PAT }}@github.com/tipsypastels/stardex-beta-preview.git
          git push -u origin main --force
